### ISSUE TITLE
Ошибки маппингов

### ISSUE THREAD

**Issue by Const-Phi** [abramson21/ORMLibrary#7]
# Disclaimer
Данный issue составлен по итогам [коммита `618c22a`](https://github.com/abramson21/ORMLibrary/commit/618c22ad39ff1b21d4a9087761bc94dc4adf2a47) из ветки [`devORM_nikolaev`](https://github.com/abramson21/ORMLibrary/compare/devORM_nikolaev).

# Суть
В ряде маппингов допущены ошибки. 
## `GenreMap` и `Genre` 
Например, в [`GenreMap`](https://github.com/abramson21/ORMLibrary/commit/618c22ad39ff1b21d4a9087761bc94dc4adf2a47#diff-019da13274cbb610052eb08ebf921c4afd45279f78aec82aa35ce58d5f432053)
```cs
    public class GenreMap : ClassMap<Genre>
    {
        public GenreMap()
        {
            this.Table("Genre");
            this.Id(x => x.Id);
            this.Id(x => x.ID_Genre);
            this.Map(x => x.Title);
            this.References(x => x.Book).ForeignKey("ID_Genre");
        }
    }
```

В данном случае дважды применён [`Id()`](https://github.com/nhibernate/fluent-nhibernate/blob/7b1030996db768637da8dc2fd31bd0095e2f5a91/src/FluentNHibernate/Mapping/ClassMap.cs#L144) &ndash; так не работает, так как первичный ключ может быть только один. Если нужен именно композитный ключ, то стоит использовать [`CompositeId()`](https://github.com/nhibernate/fluent-nhibernate/blob/7b1030996db768637da8dc2fd31bd0095e2f5a91/src/FluentNHibernate/Mapping/ClassMap.cs#L206). Но кажется, что здесь и поле `ID_Genre` и повторный вызов метода `this.Id()` 
```cs
	    this.Id(x => x.ID_Genre);
```
являются избыточными.

Метод `.ForeignKey()` для `this.References()` подразумевает внешний ключ, по которому выстраивается связь для поля сущности из `this.References()`. Соответсвенно, из строчки
```cs
            this.References(x => x.Book).ForeignKey("ID_Genre");
```
можно сделать вывод, что поле `Book` сущности `Genre` будет строится из строки таблицы `Books` по первичному ключу, значение которого лежит в столбце `ID_Genre` таблицы `Genre`.

## `BookMap`
Также есть замечание по использованию `Inverse` в маппингах. Вот цитата из [официального туториала Fluent NHibernate](https://github.com/nhibernate/fluent-nhibernate/wiki/Getting-started):
> Inverse on HasMany is an NHibernate term, and it means that the other end of the relationship is responsible for saving.

# Резюме
Стоит обсудить подробнее.

**Comment by abramson21** [comment]
Исправил! Насколько грамотно написано еще не понял, но завтра разберусь и может что-то подправлю. Pull requests открою завтра, когда доделаю то, что хочу. Спасибо за статью c [туториала](https://github.com/nhibernate/fluent-nhibernate/wiki/Getting-started) , вроде помогла 👍🏻
